services:
  db:
    image: postgres:15-alpine
    container_name: dataset_factory_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: dataset_factory
    ports:
      - "5435:5432"
    restart: unless-stopped